apiVersion: kubeadm.k8s.io/v1alpha3
kind: ClusterConfiguration
kubernetesVersion: stable
apiServerCertSANs:
- "{{ LB_DNS }}"
controlPlaneEndpoint: "{{ LB_DNS }}:{{ APISERVER_PORT }}"
etcd:
  local:
    extraArgs:
      listen-client-urls: "https://127.0.0.1:2379,https://{{ hostvars[groups['etcd_ca'][0]].ansible_default_ipv4.address }}:2379"
      advertise-client-urls: "https://{{ hostvars[groups['etcd_ca'][0]].ansible_default_ipv4.address }}:2379"
      listen-peer-urls: "https://{{ hostvars[groups['etcd_ca'][0]].ansible_default_ipv4.address }}:2380"
      initial-advertise-peer-urls: "https://{{ hostvars[groups['etcd_ca'][0]].ansible_default_ipv4.address }}:2380"
      initial-cluster: "{{ hostvars[groups['etcd_ca'][0]].ansible_hostname }}=https://{{ hostvars[groups['etcd_ca'][0]].ansible_default_ipv4.address }}:2380"
    serverCertSANs:
      - {{ hostvars[groups['etcd_ca'][0]].ansible_hostname }}
      - {{ hostvars[groups['etcd_ca'][0]].DNS_NAME }}
      - {{ hostvars[groups['etcd_ca'][0]].ansible_default_ipv4.address }}
    peerCertSANs:
      - {{ hostvars[groups['etcd_ca'][0]].ansible_hostname }}
      - {{ hostvars[groups['etcd_ca'][0]].DNS_NAME }}
      - {{ hostvars[groups['etcd_ca'][0]].ansible_default_ipv4.address }}
networking:
    serviceSubnet: "172.20.0.0/12"
kind: InitConfiguration
nodeRegistration:
  criSocket: /run/containerd/containerd.sock
