---

- name: create network wait online override dir
  file:
    path: /etc/systemd/system/systemd-networkd-wait-online.service.d/
    state: directory

- name: create override for private networks
  template:
    src: ignore-private.conf
    dest: /etc/systemd/system/systemd-networkd-wait-online.service.d/
