---
- name: install dependencies
  apt:
    name: apt-transport-https
    update_cache: yes

- name: add gpg key for kubernetes repo
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: install kubernetes repository
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes

- name: install packages
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    update_cache: yes

- name: lock package versions
  shell: apt-mark hold kubelet kubeadm kubectl

- name: set cgroup driver
  lineinfile:
    path: /etc/default/kubelet
    regexp: '^KUBELET_EXTRA_ARGS='
    line: 'KUBELET_EXTRA_ARGS=--cgroup-driver=cgroupfs --node-ip={{ WIREGUARD_SUBNET}}.{{ vpn_ip }}'
  when: CONTAINER_RUNTIME != 'docker'

- name: set cgroup driver
  lineinfile:
    path: /etc/default/kubelet
    regexp: '^KUBELET_EXTRA_ARGS='
    line: 'KUBELET_EXTRA_ARGS=--cgroup-driver=systemd --node-ip={{ WIREGUARD_SUBNET}}.{{ vpn_ip }}'
  when: CONTAINER_RUNTIME == 'docker'

- name: preserve firewall rules
  copy:
    src: wireguard-iptables.service
    dest: /etc/systemd/system/

- name: enable systemd service for preserving firewall rules
  systemd:
    name: wireguard-iptables.service
    state: restarted
    enabled: yes
    daemon-reload: yes
