apiVersion: "kubeadm.k8s.io/v1alpha3"
kind: ClusterConfiguration
etcd:
  local:
    serverCertSANs:
    - "{{ ansible_default_ipv4.address }}"
    peerCertSANs:
    - "{{ ansible_default_ipv4.address }}"
    extraArgs:
      initial-cluster: {% for h in groups['etcd'] | sort %}{{ hostvars[h].ansible_hostname }}=https://{{ hostvars[h].ansible_default_ipv4.address }}:2380{% if not loop.last %},{% endif %}{% endfor %}

      initial-cluster-state: new
      name: {{ ansible_hostname }}
      listen-peer-urls: https://{{ ansible_default_ipv4.address }}:2380
      listen-client-urls: https://{{ ansible_default_ipv4.address }}:2379
      advertise-client-urls: https://{{ ansible_default_ipv4.address }}:2379
      initial-advertise-peer-urls: https://{{ ansible_default_ipv4.address }}:2380
