---
- name: replace apt repository with local mirror
  replace:
    path: /etc/apt/sources.list
    regexp: "(archive|security)\\.ubuntu\\.com"
    replace: "{{ MIRROR_URL }}"
    backup: yes

- name: remove scaleway ppa (no ipv6)
  file:
    path: /etc/apt/sources.list.d/scaleway-ubuntu-stable-xenial.list
    state: absent

- name: get default route for private subnet
  shell: "ip r |grep default|awk '{ print $3 }'"
  register: gateway

- name: set static route to apipa
  template:
    dest: /etc/network/interfaces.d/60-apiparoute.cfg
    src: apiparoute.cfg
