---
- name: generate ssh key for ca server
  shell: ssh-keygen -t ed25519 -f /root/.ssh/id_ed25519 -q -N ""
  args:
    creates: /root/.ssh/id_ed25519
  when: inventory_hostname in groups['master-0']

- name: get ssh public key
  slurp:
    src: /root/.ssh/id_ed25519.pub
  register: ssh_public_key
  delegate_to: "{{ groups['master-0'][0] }}"

- name: add key to authorized keys
  authorized_key:
    user: root
    key: "{{ ssh_public_key.content | b64decode }}" 
  when: inventory_hostname not in groups['master-0']

