---
- name: install haproxy
  apt:
    name: haproxy
    update-cache: yes

- name: copy haproxy config
  template:
    src: haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg

- name: enable fw rules for apiserver
  iptables_raw:
    name: kube-apiserver
    state: present
    weight: 15
    keep_unmanaged: no
    ipversion: "{{ item }}"
    rules: |
      -A TCP -p tcp --dport 6443 -j ACCEPT
  loop:
    - 4
    - 6
  tags: iptables

- name: restart haproxy
  systemd:
    name: haproxy
    state: restarted
