---
- name: generate keypairs
  shell: 'umask 077; wg genkey | tee privatekey | wg pubkey > publickey'
  args:
    chdir: /etc/wireguard
    creates: privatekey
  tags: wireguard-config

- name: get public keys
  slurp:
    src: /etc/wireguard/publickey
  register: public_key
  tags: wireguard-config

- name: get private keys
  slurp:
    src: /etc/wireguard/privatekey
  register: private_key
  tags: wireguard-config

- name: create active/passive dirs
  file:
    state: directory
    path: "/etc/wireguard/{{ item }}"
  loop:
    - active
    - passive
  tags: wireguard-config

- name: create endpoint config
  template:
    src: wg0.conf.j2
    dest: /etc/wireguard/active/wg0.conf
    mode: 0600
  when: "'proxies' in group_names"
  tags: wireguard-config

- name: create client config for normal clients
  template:
    src: tunnel.conf.j2
    dest: /etc/wireguard/tunnel_{{ idx }}.conf
    mode: 0600
  loop: "{{ groups['proxies'] | sort }}"
  loop_control:
    index_var: idx
  when: "'proxies' not in group_names"
  tags: wireguard-config

- name: create client config for endpoints
  template:
    src: tunnel.conf.j2
    dest: /etc/wireguard/passive/wg0.conf
    mode: 0600
  loop: "{{ groups['proxies'] }}"
  when: "'proxies' in group_names and item != inventory_hostname"
  tags: wireguard-config
