---
- name: Install necessary packages
  apt:
    name:
      - build-essential
      - libmnl-dev
      - libelf-dev
      - pkg-config
      - "linux-headers-{{ ansible_kernel }}"
    state: latest
    update_cache: yes

- name: Extract sources
  unarchive:
    src: "https://git.zx2c4.com/WireGuard/snapshot/WireGuard-{{ WIREGUARD_VERSION }}.tar.xz"
    dest: /usr/local/src
    remote_src: yes

- name: Compile WireGuard
  make:
    chdir: "/usr/local/src/WireGuard-{{ WIREGUARD_VERSION }}/src/"

- name: Install WireGuard
  make:
    chdir: "/usr/local/src/WireGuard-{{ WIREGUARD_VERSION }}/src/"
    target: install

- name: load WireGuard kernel module
  modprobe:
    name: wireguard
    state: present
