---
- name: add apt key
	apt_key:
		keyserver: keys.gnupg.net
		id: E1B39B6EF6DDB96564797591AE33835F504A1A25

- name: add wireguard ppa (ipv6 proxy)
	apt_repository:
		repo: "http://ppa.{{ MIRROR_DOMAIN }}/wireguard/wireguard/ubuntu/ xenial main"
		state: present

- name: install wireguard
	apt:
		name: wireguard
		state: present
		update-cache: yes
