---
- name: Open ports in iptables
  iptables_raw:
    name: wireguard_open_ports
    state: present
    weight: 1
    rules: |
      -A INPUT -p udp --dport {{ WIREGUARD_PORT }} -j ACCEPT
      -A UDP -p udp --dport {{ WIREGUARD_PORT }} -j ACCEPT
      -A OUTPUT -p udp --sport {{ WIREGUARD_PORT }} -j ACCEPT
  tags: iptables,wireguard-config

- name: enable forwarding rules for proxies
  iptables_raw:
    name: wireguard_forwarding
    state: present
    weight: 10
    rules: |
      -A FORWARD -i wg0 -j ACCEPT
      -A FORWARD -o wg0 -j ACCEPT
  tags: iptables,wireguard-config
  when: "'proxies' in group_names"

- name: wireguard nat rules
  iptables_raw:
    name: wireguard_nat
    state: present
    weight: 10
    table: nat
    rules: "-A POSTROUTING -o {{ ansible_default_ipv4.interface }} -j MASQUERADE"
  tags: iptables,wireguard-config
  when: "'proxies' in group_names"
