---
- name: enable ip forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
  when: "'proxies' in group_names"

- name: install wireguard (from source)
  include_tasks: install_source.yml
  when: COMPILE_WIREGUARD == true

- name: install wireguard
  include_tasks: install_ppa.yml
  when: COMPILE_WIREGUARD == false

- name: check if host has public ip
  shell: scw-metadata|grep PUBLIC_IP_ADDRESS
  register: PUBLIC_IP
  tags: wireguard-config
  ignore_errors: true

- name: configure wireguard
  include_tasks: config.yml
  tags: wireguard-config

- name: setup failover for clients
  include_tasks: failover.yml
  when: "'proxies' not in group_names"
  tags: wireguard-config

- name: setup iptables rules
  include_tasks: iptables.yml
  tags: iptables, wireguard-config

- name: enable wireguard endpoint active
  shell: "wg-quick down /etc/wireguard/active/wg0.conf && wg-quick up /etc/wireguard/active/wg0.conf"
  when: "PUBLIC_IP.rc == 0 and 'proxies' in group_names"
  tags: wireguard-config

- name: enable wireguard endpoint passive
  shell: "wg-quick down /etc/wireguard/passive/wg0.conf && wg-quick up /etc/wireguard/passive/wg0.conf"
  when: "PUBLIC_IP.rc == 1 and 'proxies' in group_names"
  tags: wireguard-config

- name: enable wireguard clients
  systemd:
    name: wg-quick@tunnel_0
    state: restarted
    daemon-reload: yes
    enabled: yes
  when: "'proxies' not in group_names"
  tags: wireguard-config
