---
- name: install wireguard
  include_tasks: install.yml

- name: configure wireguard
  include_tasks: config.yml

- name: setup failover for clients
  include_tasks: failover.yml
  when: "'proxies' not in group_names"

- name: setup iptables rules
  include_tasks: iptables.yml
  tags: iptables

- name: enable wireguard endpoints
  systemd:
    name: wg-quick@wg0
    state: restarted
    daemon-reload: yes
    enabled: yes
  when: "'proxies' in group_names"

- name: enable wireguard clients
  systemd:
    name: wg-quick@tunnel_0
    state: restarted
    daemon-reload: yes
    enabled: yes
  when: "'proxies' not in group_names"

