---
- name: generate keypairs
  shell: 'umask 077; wg genkey | tee privatekey | wg pubkey > publickey'
  args:
    chdir: /etc/wireguard
    creates: privatekey

- name: get public keys
  fetch:
    src: /etc/wireguard/publickey
    dest: "./roles/wireguard/files/{{ inventory_hostname }}"
    flat: yes
