---
- name: override kubelet unit file
  copy:
    src: 20-etcd-service-manager.conf
    dest: /etc/systemd/system/kubelet.service.d/20-etcd-service-manager.conf

- name: restart kubelet
  systemd:
    name: kubelet
    daemon-reload: yes
    state: restarted

- name: add kubeadm config
  template:
    src: kubeadmcfg.yaml
    dest: /tmp/

- name: generate etcd ca
  shell: kubeadm alpha phase certs etcd-ca
  args:
    creates: /etc/kubernetes/pki/etcd/ca.crt
  when: inventory_hostname in groups['etcd_ca']

- name: generate ssh key for ca server
  shell: ssh-keygen -t ed25519 -f /root/.ssh/id_ed25519 -q -N ""
  args:
    creates: /root/.ssh/id_ed25519
  when: inventory_hostname in groups['etcd_ca']

- name: get ssh public key
  slurp:
    src: /root/.ssh/id_ed25519.pub
  register: ssh_public_key
  delegate_to: "{{ groups['etcd_ca'][0] }}"

- name: add key to authorized keys
  authorized_key:
    user: root
    key: "{{ ssh_public_key.content | b64decode }}" 
  when: inventory_hostname in groups['etcd_noca']

- name: make sure etcd pki dir exists
  file:
    path: /etc/kubernetes/pki/etcd/
    state: directory

- name: copy ca to other hosts
  synchronize:
    src: "/etc/kubernetes/pki/etcd/{{ item }}"
    dest: "/etc/kubernetes/pki/etcd/{{ item }}"
  loop:
    - ca.crt
    - ca.key
  delegate_to: "{{ groups['etcd_ca'][0] }}"
  when: inventory_hostname in groups['etcd_noca']

- name: create certs
  shell: "kubeadm alpha phase certs {{ item.command}} --config=/tmp/kubeadmcfg.yaml"
  args:
    creates: "/etc/kubernetes/pki/{{ item.file }}"
  loop:
    - { command: 'etcd-server', file: '/etcd/server.crt' }
    - { command: 'etcd-peer', file: '/etcd/peer.crt' }
    - { command: 'etcd-healthcheck-client', file: '/etcd/healthcheck-client.crt' }
    - { command: 'apiserver-etcd-client', file: 'apiserver-etcd-client.crt' }
