---
- name: override kubelet unit file
  copy:
    src: 20-etcd-service-manager.conf
    dest: /etc/systemd/system/kubelet.service.d/20-etcd-service-manager.conf

- name: restart kubelet
  systemd:
    name: kubelet
    daemon-reload: yes
    state: restarted

- name: add kubeadm config
  template:
    src: kubeadmcfg.yaml
    dest: /tmp/
