---
- name: install iptables-persistent
  apt:
    name: iptables-persistent
    state: present
    update-cache: true

- name: setup protocol specific chains
  iptables_raw:
    name: protocol_chains
    state: present
    rules: "{{ custom_chains }}"
    ipversion: "{{ item }}"
  loop:
    - 4
    - 6

- name: setup default head rules
  iptables_raw:
    name: default_rules_head
    weight: 10
    state: present
    rules: "{{ item.rule }}"
    ipversion: "{{ item.v }}"
  loop:
    - { v: 4, rule: default_rules_head_v4 }
    - { v: 6, rule: default_rules_head_v6 }

- name: setup icmp flood chain
  iptables_raw:
    name: icmp_flood_rate_limit
    weight: 10
    state: present
    rules: "{{ default_icmp_flood }}"
    ipversion: "{{ item }}"
  loop:
    - 4
    - 6

- name: block packets claiming to be from loopback
  iptables_raw:
    name: block_fake_loopback
    weight: 11
    state: present
    rules: "{{ item.rule }}"
    ipversion: "{{ item.v }}"
  loop:
    - { v: 4, rule: default_rules_fake_v4}
    - { v: 6, rule: default_rules_fake_v6 }

- name: setup default tcp rules
  iptables_raw:
    name: default_tcp_rules
    weight: 10
    state: present
    rules: "{{ default_tcp }}"
    ipversion: "{{ item }}"
  loop:
    - 4
    - 6

- name: setup default icmp rules
  iptables_raw:
    name: default_icmp_rules
    weight: 10
    state: present
    rules: "{{ item.rule }}"
    ipversion: "{{ item.v }}"
  loop:
    - { v: 4, rule: default_icmp_v4}
    - { v: 6, rule: default_icmp_v6 }

- name: setup default policies
  iptables_raw:
    name: default_policies
    state: present
    rules: "{{ default_policies }}"
    ipversion: "{{ item }}"
  loop:
    - 4
    - 6
