---
- name: install iptables-persistent
  apt:
    name: iptables-persistent
    state: present
    update-cache: true

- name: setup protocol specific chains
  iptables_raw:
    name: protocol_chains
    state: present
    rules: "{{ custom_chains }}"
    keep_unmanaged: no
    ipversion: "{{ item }}"
  loop:
    - 4
    - 6

- name: setup default head rules
  iptables_raw:
    name: default_rules_head
    weight: 10
    state: present
    rules: "{{ item.rule }}"
    keep_unmanaged: no
    ipversion: "{{ item.v }}"
  loop:
    - { v: 4, rule: "{{ default_rules_head_v4 }}" }
    - { v: 6, rule: "{{ default_rules_head_v6 }}" }

- name: setup icmp flood chain
  iptables_raw:
    name: icmp_flood_rate_limit
    weight: 10
    state: present
    rules: "{{ default_icmp_flood }}"
    keep_unmanaged: no
    ipversion: "{{ item }}"
  loop:
    - 4
    - 6

- name: block packets claiming to be from loopback
  iptables_raw:
    name: block_fake_loopback
    weight: 11
    state: present
    rules: "{{ item.rule }}"
    keep_unmanaged: no
    ipversion: "{{ item.v }}"
  loop:
    - { v: 4, rule: "{{ default_rules_fake_v4 }}" }
    - { v: 6, rule: "{{ default_rules_fake_v6 }}" }

- name: setup default tcp rules
  iptables_raw:
    name: default_tcp_rules
    weight: 10
    state: present
    rules: "{{ default_tcp }}"
    keep_unmanaged: no
    ipversion: "{{ item }}"
  loop:
    - 4
    - 6

- name: setup default udp rules
  iptables_raw:
    name: default_udp_rules
    weight: 10
    state: present
    rules: "{{ item.rule }}"
    keep_unmanaged: no
    ipversion: "{{ item.v }}"
  loop:
    - { v: 4, rule: "{{ default_udp_v4 }}" }
    - { v: 6, rule: "{{ default_udp_v6 }}" }

- name: setup default icmp rules
  iptables_raw:
    name: default_icmp_rules
    weight: 10
    state: present
    rules: "{{ item.rule }}"
    keep_unmanaged: no
    ipversion: "{{ item.v }}"
  loop:
    - { v: 4, rule: "{{ default_icmp_v4 }}" }
    - { v: 6, rule: "{{ default_icmp_v6 }}" }

- name: setup default policies
  iptables_raw:
    name: default_policies
    state: present
    rules: "{{ default_policies }}"
    keep_unmanaged: no
    ipversion: "{{ item }}"
  loop:
    - 4
    - 6

- name: enable fw rules for weave
  iptables_raw:
    name: weavenet
    state: present
    weight: 20
    ipversion: "{{ item }}"
    keep_unmanaged: no
    rules: |
      -A TCP -p tcp --dport 6783 -j ACCEPT
      -A UDP -p udp --dport 6783 -j ACCEPT
      -A UDP -p udp --dport 6784 -j ACCEPT
  loop:
    - 4
    - 6
  tags: iptables

- name: enable fw rules for kubelet-api
  iptables_raw:
    name: kubelet-api
    state: present
    weight: 16
    keep_unmanaged: no
    rules: |
      -A TCP -p tcp --dport 10250 -s 172.16.0.0/12,192.168.100.0/24 -j ACCEPT
  tags: iptables
