---
- name: create weave dir
  file:
    path: /var/lib/weave
    state: directory

- name: generate random password
  template:
    src: weave-passwd
    dest: /var/lib/weave/weave-passwd

- name: create kubernetes secret
  shell: kubectl create secret -n kube-system generic weave-passwd --from-file=/var/lib/weave/weave-passwd
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  run_once: true

- name: download weave manifest
  get_url:
    url: "https://cloud.weave.works/k8s/net?k8s-version={{ KUBERNETES_VERSION }}&password-secret=weave-passwd"
    dest: /tmp/weave.yaml

- name: adjust cidr
  replace:
    dest: /tmp/weave.yaml
    regexp: "^\\s{14}command:\\n\\s{16}\\- \\/home\\/weave\\/launch.sh\\n\\s{14}env:\\n\\s{16}\\- name: HOSTNAME"
    replace: "              command:\n                 - \/home\/weave\/launch.sh\n\              env:\n\                - name: IPALLOC_RANGE\n                  value: {{ SERVICE_SUBNET }}\n                - name: HOSTNAME"

- name: apply weave net
  shell: kubectl apply -f /tmp/weave.yaml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  run_once: true

- name: enable fw rules for apiserver
  iptables_raw:
    name: weavenet
    state: present
    weight: 20
    ipversion: "{{ item }}"
    keep_unmanaged: no
    rules: |
      -A TCP -p tcp --dport 6783 -j ACCEPT
      -A UDP -p udp --dport 6783 -j ACCEPT
      -A UDP -p udp --dport 6784 -j ACCEPT
  loop:
    - 4
    - 6
  tags: iptables
