apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: user-request-{{ USER }}
spec:
  groups:
  - system:authenticated
  request: {{ CSR['content'] }}
  usages:
  - digital signature
  - key encipherment
  - client auth
