apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: {{ CA.stdout }}
    server: https://{{ LB_DNS }}:6443
  name: {{ DOMAIN }}
contexts:
- context:
    cluster: {{ DOMAIN }}
    user: {{ USER }}
  name: {{ USER }}@{{ DOMAIN }}
current-context: {{ USER }}@{{ DOMAIN }}
kind: Config
preferences: {}
users:
- name: {{ USER }}
  user:
    client-certificate-data: {{ CERT.stdout | b64encode }}
    client-key-data: {{ KEY.content }}
