---
- hosts: proxies
  roles:
    - { role: router, tags: ["router"] }

- hosts: masters
  roles:
    - { role: natted, tags: ["router"] }

- hosts: all
  roles:
    - { role: common, tags: ["initial"] }
