---
- hosts: proxies
  roles:
    - { role: router, tags: ["router"] }

- hosts: masters
  roles:
    - { role: natted, tags: ["router"] }

- hosts: all
  roles:
    - { role: prepare, tags: ["prepare"] }
    - { role: wireguard, tags: ["wireguard"] }
    - { role: update, tags: ["update"], serial: "30%" }

- hosts: kube-hosts
  roles:
    - { role: cri-o, when: CONTAINER_RUNTIME == 'cri-o', tags: ["kubernetes", "runtime"] } # choose either cri-o or containerd or docker
    - { role: docker, when: CONTAINER_RUNTIME == 'docker', tags: ["kubernetes", "runtime"] }
    - { role: containerd, when: CONTAINER_RUNTIME == 'containerd', tags: ["kubernetes", "runtime"] }
    - { role: kubernetes-tools, tags: ["kubernetes", "kube-tools"] }

- hosts: etcd
  roles:
    - { role: kubeadm-etcd, tags: ["kubernetes", "etcd"] } # use this if doing a external etcd cluster
