---
- hosts: all
  roles:
    - { role: common }

- hosts: proxies
  roles:
    - { role: router, tags: ["router"] }

- hosts: masters
  roles:
    - { role: natted }

- hosts: all
  roles:
    - { role: wireguard-setup }
