---
- hosts: proxies
  roles:
    - { role: router, when: env == 'local', tags: ["router"] }

- hosts: masters
  roles:
    - { role: natted, when: env == 'local', tags: ["router"] }

- hosts: all
  vars_files: group_vars/private.yml
  roles:
    - { role: common, tags: ["common"] }
    - { role: iptables, tags: ["iptables"] }
    - { role: wireguard, tags: ["wireguard"] }
    - { role: update, tags: ["update"], serial: "30%" }
    - { role: fakedns, when: env == 'local', tags: ["fakedns"] }

- hosts: proxies
  vars_files: group_vars/private.yml
  roles:
    - { role: haproxy, tags: ["haproxy"] }

- hosts: kube-hosts
  vars_files: group_vars/private.yml
  roles:
    - { role: cri-o, when: CONTAINER_RUNTIME == 'cri-o', tags: ["kubernetes", "runtime"] } # choose either cri-o or containerd or docker
    - { role: docker, when: CONTAINER_RUNTIME == 'docker', tags: ["kubernetes", "runtime"] }
    - { role: containerd, when: CONTAINER_RUNTIME == 'containerd', tags: ["kubernetes", "runtime"] }
    - { role: kube-tools, tags: ["kubernetes", "kube-tools"] }

- hosts: masters
  vars_files: group_vars/private.yml
  roles:
    - { role: ssh, tags: ["bootstrap", "etcd", "ssh"] }
    - { role: kubeadm, tags: ["bootstrap", "kubeadm"] }
    - { role: weave, tags: ["bootstrap", "weave"] }

- hosts: etcd
  roles:
    - { role: etcd, tags: ["etcd"] } # use this if doing a external etcd cluster

- hosts: localhost
  vars_files: group_vars/private.yml
  roles:
    - { role: cluster-access, tags: ["cluster-access"] }
