---
- hosts: proxies
  roles:
    - { role: router, tags: ["router"] }

- hosts: masters
  roles:
    - { role: natted, tags: ["router"] }

- hosts: all
  roles:
    - { role: prepare, tags: ["prepare"] }
    - { role: wireguard, tags: ["wireguard"] }
    - { role: update, tags: ["update"], serial: "30%" }

- hosts: kube-hosts
  roles:
    #    - { role: cri-o, tags: ["kubernetes"] }
    - { role: containerd, tags: ["kubernetes", "runtime"] }
    - { role: kubernetes-tools, tags: ["kubernetes", "kube-tools"] }
    - { role: kubeadm-etcd, tags: ["kubernetes", "etcd"] }
