---
- hosts: proxies
  roles:
    - { role: router, when: env == 'local', tags: ["router"] }

- hosts: masters
  roles:
    - { role: natted, when: env == 'local', tags: ["router"] }

- hosts: all
  roles:
    - { role: prepare, tags: ["prepare"] }
    - { role: update, tags: ["update"], serial: "30%" }
    - { role: wireguard, tags: ["wireguard"] }
    - { role: fakedns, when: env == 'local', tags: ["fakedns"] }
    - { role: iptables, tags: ["iptables"] }

- hosts: kube-hosts
  roles:
    - { role: cri-o, when: CONTAINER_RUNTIME == 'cri-o', tags: ["kubernetes", "runtime"] } # choose either cri-o or containerd or docker
    - { role: docker, when: CONTAINER_RUNTIME == 'docker', tags: ["kubernetes", "runtime"] }
    - { role: containerd, when: CONTAINER_RUNTIME == 'containerd', tags: ["kubernetes", "runtime"] }
    - { role: kubernetes-tools, tags: ["kubernetes", "kube-tools"] }
    - { role: ssh, tags: ["kubernetes", "etcd", "ssh"] }
    - { role: kubeadm, tags: ["kubernetes", "kubeadm"] }
    - { role: weave, tags: ["kubernetes", "weave"] }

- hosts: etcd
  roles:
    - { role: etcd, tags: ["etcd"] } # use this if doing a external etcd cluster

- hosts: proxies
  roles:
    - { role: haproxy, tags: ["haproxy"] }
