---
custom_chains: |
  -N TCP
  -N UDP
  -N ICMP

default_policies: |
  -P INPUT DROP
  -P FORWARD DROP
  -P OUTPUT ACCEPT

default_rules_head: |
  -A INPUT -i lo -j ACCEPT
  -A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
  -A INPUT -m conntrack --ctstate INVALID -j DROP
  -A INPUT -p udp -m conntrack --ctstate NEW -j UDP
  -A INPUT -p tcp --syn -m conntrack --ctstate NEW -j TCP
  -A INPUT -p icmp -m conntrack --ctstate NEW -j ICMP

default_rules_tail: |
  -A INPUT -p udp -j REJECT --reject-with icmp-port-unreachable
  -A INPUT -p tcp -j REJECT --reject-with tcp-reset
  -A INPUT -j REJECT --reject-with icmp-proto-unreachable
  -A FORWARD -p udp -j REJECT --reject-with icmp-port-unreachable
  -A FORWARD -p tcp -j REJECT --reject-with tcp-reset
  -A FORWARD -j REJECT --reject-with icmp-proto-unreachable

default_tcp:
  -A TCP -p tcp --dport 22 -j ACCEPT

default_icmp:
  -A ICMP -p icmp --icmp-type echo-request -j ACCEPT
