---
- name: get current kernel
  set_fact:
    old_kernel: "{{ ansible_kernel }}"

- name: update apt cache
  apt:
    update_cache: yes

- name: upgrade packages
  apt:
    upgrade: dist

- name: Check if reboot is required
  stat:
    path: /var/run/reboot-required
    get_md5: no
  register: reboot_required_file

- name: reboot
  reboot:
  when: reboot_required_file.stat.exists == true

- name: get current kernel
  set_fact:
    new_kernel: "{{ ansible_kernel }}"

- name: compile and install wireguard
  make:
    chdir: "/usr/local/src/WireGuard-{{ WIREGUARD_VERSION }}/src/"
    target: install
  when: old_kernel != new_kernel
  notify:
    - load WireGuard kernel module

- name: remove unneeded packages
  apt:
    autoremove: yes
