---
- name: enable fw rules for apiserver
  iptables_raw:
    name: kube-apiserver
    state: present
    weight: 15
    keep_unmanaged: no
    ipversion: "{{ item }}"
    rules: |
      -A TCP -p tcp --dport 6443 -j ACCEPT
  loop:
    - 4
    - 6
  tags: iptables

- name: enable fw rules for etcd
  iptables_raw:
    name: etcd
    state: present
    weight: 15
    keep_unmanaged: no
    ipversion: "{{ item }}"
    rules: |
      -A TCP -p tcp --dport 2379:2380 -j ACCEPT
  loop:
    - 4
    - 6
  tags: iptables

- name: enable fw rules for kubelet-api
  iptables_raw:
    name: kubelet-api
    state: present
    weight: 16
    keep_unmanaged: no
    ipversion: "{{ item }}"
    rules: |
      -A TCP -p tcp --dport 10250 -j ACCEPT
  loop:
    - 4
    - 6
  tags: iptables
