---
- name: enable fw rules for apiserver
  iptables_raw:
    name: kube-apiserver
    state: present
    weight: 15
    ipversion: "{{ item }}"
    rules: |
      -A TCP -p tcp --dport 6443 -j ACCEPT
  loop:
    - 4
    - 6
  tags: iptables

- name: enable fw rules for etcd
  iptables_raw:
    name: etcd
    state: present
    weight: 15
    ipversion: "{{ item }}"
    rules: |
      -A TCP -p tcp --dport 2379:2380 -j ACCEPT
  loop:
    - 4
    - 6
  tags: iptables

- name: enable fw rules for kubelet-api
  iptables_raw:
    name: kubelet-api
    state: present
    weight: 15
    ipversion: "{{ item }}"
    rules: |
      -A TCP -p tcp --dport 10250 -j ACCEPT
  loop:
    - 4
    - 6
  tags: iptables

- name: enable fw rules for kube-scheduler
  iptables_raw:
    name: kube-scheduler
    state: present
    weight: 15
    ipversion: "{{ item }}"
    rules: |
      -A TCP -p tcp --dport 10251 -j ACCEPT
  loop:
    - 4
    - 6
  tags: iptables

- name: enable fw rules for kube-controller-manager
  iptables_raw:
    name: kube-controller-manager
    state: present
    weight: 15
    ipversion: "{{ item }}"
    rules: |
      -A TCP -p tcp --dport 10252 -j ACCEPT
  loop:
    - 4
    - 6
  tags: iptables

- name: copy kubeadm config
  template:
    src: kubeadm-config.yaml
    dest: /tmp/

- name: run kubeadm init on first node
  shell: kubeadm init --config /tmp/kubeadm-config.yaml
  args:
    creates: /etc/kubernetes/pki/ca.crt
  when: inventory_hostname in groups['master-0']
  register: kubeadm_init

- debug:
    msg: "{{ hostvars[groups['master-0'][0]].kubeadm_init.stdout_lines | last }}"

- name: make sure the kubernetes folder exists
  file:
    path: /etc/kubernetes/pki/etcd
    state: directory

- name: copy generated config and certs to other hosts
  synchronize:
    src: "{{ item }}"
    dest: "{{ item }}"
  loop:
    - /etc/kubernetes/pki/ca.crt
    - /etc/kubernetes/pki/ca.key
    - /etc/kubernetes/pki/sa.pub
    - /etc/kubernetes/pki/sa.key
    - /etc/kubernetes/pki/front-proxy-ca.crt
    - /etc/kubernetes/pki/front-proxy-ca.key
    - /etc/kubernetes/pki/etcd/ca.crt
    - /etc/kubernetes/pki/etcd/ca.key
    - /etc/kubernetes/admin.conf
  delegate_to: "{{ groups['master-0'][0] }}"
  when: inventory_hostname not in groups['master-0']

- name: setup config and start kubelet on second node
  include_tasks: kubelet.yml
  when: inventory_hostname in groups['master-1']

- name: wait for etcd
  wait_for:
    timeout: 60
  when: inventory_hostname in groups['master-1']

- name: join second node to cluster
  include_tasks: join.yml
  when: inventory_hostname in groups['master-1']

- name: setup config and start kubelet on third node
  include_tasks: kubelet.yml
  when: inventory_hostname in groups['master-2']

- name: join third node to cluster
  include_tasks: join.yml
  when: inventory_hostname in groups['master-2']

