---
- name: add firewall rules
  include_tasks: iptables.yml
  tags: iptables,initial_node

- name: copy kubeadm config
  template:
    src: kubeadm-config.yaml
    dest: /tmp/
  tags: initial_node

- name: run kubeadm init on first node
  shell: kubeadm init --config /tmp/kubeadm-config.yaml
  args:
    creates: /etc/kubernetes/pki/ca.crt
  when: inventory_hostname in groups['master-0']
  register: kubeadm_init
  tags: initial_node

- name: make sure the kubernetes folder exists
  file:
    path: /etc/kubernetes/pki/etcd
    state: directory
  tags: second_node

- name: copy generated config and certs to other hosts
  synchronize:
    src: "{{ item }}"
    dest: "{{ item }}"
  loop:
    - /etc/kubernetes/pki/ca.crt
    - /etc/kubernetes/pki/ca.key
    - /etc/kubernetes/pki/sa.pub
    - /etc/kubernetes/pki/sa.key
    - /etc/kubernetes/pki/front-proxy-ca.crt
    - /etc/kubernetes/pki/front-proxy-ca.key
    - /etc/kubernetes/pki/etcd/ca.crt
    - /etc/kubernetes/pki/etcd/ca.key
    - /etc/kubernetes/admin.conf
  delegate_to: "{{ groups['master-0'][0] }}"
  when: inventory_hostname not in groups['master-0']
  tags: second_node

- name: setup config and start kubelet on second node
  include_tasks: kubelet.yml
  when: inventory_hostname in groups['master-1']
  tags: second_node

- name: wait for etcd
  wait_for:
    timeout: 60
  when: inventory_hostname in groups['master-1']

- name: join second node to cluster
  include_tasks: join.yml
  when: inventory_hostname in groups['master-1']
  tags: second_node_join

- name: setup config and start kubelet on third node
  include_tasks: kubelet.yml
  when: inventory_hostname in groups['master-2']
  tags: third_node

- name: join third node to cluster
  include_tasks: join.yml
  when: inventory_hostname in groups['master-2']
  tags: third_node_join

